# Generated by Django 5.2.8 on 2025-11-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('events', '0002_remove_event_datetime_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.event'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percent',
            field=models.PositiveIntegerField(verbose_name='درصد تخفیف'),
        ),
    ]
