# Generated by Django 5.2.8 on 2025-11-11 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discountcode_is_active_discountcode_usage_limit_and_more'),
        ('events', '0002_remove_event_datetime_event_capacity_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='used_discount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='applied_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discountcode'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ نهایی (تومان)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نام'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='کد بلیط'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event'),
        ),
    ]
